language: python
python:
  - "3.7"
services:
  - docker
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
# command to run tests
script:
  - poetry run task test
