language: python
python:
  - "3.8"
services:
  - docker
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
# command to run tests
jobs:
  include:
    - stage: "unit tests"
      script: poetry run task test
    - stage: "integration tests"
      script: poetry run task test_integration
