name: Automated testing

on:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Unit tests
        run: poetry run task test
        env:
          CONFIG_FILE: "config-test.json"
      - name: Cleanup subscription config
        run: rm subscriptions.json
      - name: Integration tests
        if: github.event_name == 'schedule' || ( ( github.event_name == 'pull_request' || github.event_name == 'push' ) && github.ref == 'refs/heads/master' )
        run: poetry run task test_integration
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          CLIENT_API_HASH: ${{ secrets.CLIENT_API_HASH }}
          CLIENT_API_ID: ${{ secrets.CLIENT_API_ID }}
          CLIENT_SESSION_STRING: ${{ secrets.CLIENT_SESSION_STRING }}
          CONFIG_FILE: "config-test.json"
