name: Automated testing

on:
  schedule:
    - cron: "0 4 * * *"
  push:
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Unit tests
        run: poetry run task test
        env:
          CONFIG_FILE: "config-test.json"

  integration_tests:
    if: |
      github.event_name == 'schedule'
      || ( github.event_name == 'push' && github.ref == 'refs/heads/master' )
      || ( github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' )
    runs-on: ubuntu-20.04
    concurrency: telegram_tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Unit tests
        run: poetry run task test
        env:
          CONFIG_FILE: "config-test.json"
      - name: Cleanup subscription config
        run: rm subscriptions.json
      - name: Site integration tests
        run: poetry run task test_site_integration
        env:
          E621_USERNAME: ${{ secrets.E621_USERNAME }}
          E621_API_KEY: ${{ secrets.E621_API_KEY }}
      - name: Telegram integration tests
        run: poetry run task test_telegram_integration
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          CLIENT_API_HASH: ${{ secrets.CLIENT_API_HASH }}
          CLIENT_API_ID: ${{ secrets.CLIENT_API_ID }}
          CLIENT_SESSION_STRING: ${{ secrets.CLIENT_SESSION_STRING }}
          E621_USERNAME: ${{ secrets.E621_USERNAME }}
          E621_API_KEY: ${{ secrets.E621_API_KEY }}
          CONFIG_FILE: "config-test.json"
