name: Unit tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [*]
  pull_request:
    branches: [*]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Unit tests
        run: poetry run task test
        with:
          CONFIG_FILE: "config-test.json"